### ISSUE TITLE
Script with argv '(null)'

### ISSUE THREAD

**Issue by saeedesmaili** [zeitlings/alfred-quill#1]
When using the workflow with a hot-key, I get empty results most of the time (but it works sometimes, I can't understand when). Here are the debugging logs:

<img width="521" alt="image" src="https://github.com/zeitlings/alfred-quill/assets/13351748/a113a9c4-9b7b-4fc9-8a9f-3a181e7c8017">

**Comment by zeitlings** [comment]
Did you set up custom Hotkeys? 
Which functions are you calling? 
What does the "Prefix" in the Hotkey utility look like?

<img width="535" alt="Screenshot 2024-01-22 at 21 28 12" src="https://github.com/zeitlings/alfred-quill/assets/25689591/70e020a8-d55c-4542-95a0-70221f1d7429">

**Comment by saeedesmaili** [comment]
Yes, here is how it's set up:
<img width="544" alt="image" src="https://github.com/zeitlings/alfred-quill/assets/13351748/601f3da6-f682-4ded-b511-e2dd04aeded8">

**Comment by zeitlings** [comment]
I guess that's to launch the workflow and show all available options (top left utility element on the Alfred canvas). So no custom hotkey. Selecting text, launching the workflow with the hotkey (thus passing through the selected text), and selecting a command (which command for example on which selected text?) fails, i.e. the transformed text is not pasted to the frontmost app or copied to the clipboard?

How do you proceed exactly?
What outcome do you expect?

If you could describe or record what you are doing and trying to achieve, provide a reproducible example, I may be able to help.

**Comment by saeedesmaili** [comment]
Yes, here it is:
<img width="487" alt="image" src="https://github.com/zeitlings/alfred-quill/assets/13351748/e97d3d73-26ed-4982-817d-542932fe4f3c">

I thought this how should I set a custom hotkey. What's the correct way of setting one?

The way I'm trying to use the workflow is to select a text, trigger the workflow with my hotkey, and I expect to view the commands in alfred for text transformation. But (as you can see in the recording below) a command appears for a moment, and then I can do nothing on alfred with the selected text. I'd like to be able to choose between text transformation commands (uppercase, lowercase, etc) after selecting a text and triggering the workflow.

![image](https://github.com/zeitlings/alfred-quill/assets/13351748/35f65374-38ae-4942-88f1-b51348131a00)

**Comment by zeitlings** [comment]
Hey, thanks for the insight. First things first, it appears you're using v0.1.0 while [v1.1.0](https://github.com/zeitlings/alfred-quill/releases/latest) is available. Perhaps updating resolves the issue already; the approach and desired outcome you describe are exactly how it should work. 

There are some examples for custom hotkeys in the workflow, in the lower half of the canvas. 
For setting up specific triggers have a look at [**Automation**](https://github.com/zeitlings/alfred-quill?tab=readme-ov-file#automation).

(fyi, unfortunately your recording became a still image)

**Comment by saeedesmaili** [comment]
Ah sorry for the recording, didn't notice it's been saved as an image. Also thanks for pointing out the new version of the workflow. I'm watching the new releases on the repo, but I have missed that there's been a new version of the workflow. I updated it and it seems to be working fine at the moment (not sure if it's actually fixed or it's one of the occasions that it was working fine randomly).

I'll update you here if the issue happens again.
