### ISSUE TITLE
Request: Sentence case

### ISSUE THREAD

**Issue by saeedesmaili** [zeitlings/alfred-quill#2]
Can we have a "sentence case" command? Sometimes I copy a "title case" text from somewhere and I want to transform it to have an uppercase letter only at the beginning of the text. Example:

From: "Allocate the Right Amount of Memory"
To: "Allocate the right amount of memory"

**Comment by zeitlings** [comment]
Hey @saeedesmaili, can you think of other use cases where this would make sense? In your case, I would just select the entire sentence except for the first letter and apply the lowercase transformation.

**Comment by saeedesmaili** [comment]
Yeah that's something I hadn't thought of and it would definitely work.
