### ISSUE TITLE
A way to combine text transformations

### ISSUE THREAD

**Issue by ognistik** [zeitlings/alfred-quill#3]
Just found this Workflow and it's super helpful. I'm using it mostly with my own automations, and I am not sure if this is already possible (could not find any example in the workflow or documentation) but it would be great to be able to chain multiple transformations.

For example:
|wrap|quotes|Ͽ|wrap|curly|Ͽ
So that it would first wrap in {"quotes and then in curly"}, the same string.

Or, what I need it for most, do multiple replacements on one go.

Amazing work, thank you for sharing.

**Comment by zeitlings** [comment]
Hey @ognistik 
Thanks! I'm glad you find it useful. While it's possible to chain commands, the current method isn't very elegant. I'll consider implementing a more streamlined internal chain evaluation, similar to something like`|wrap|quotes|+|wrap|curly|+|transform|uppercase|`.

In the meantime, here's an implementation of your example:

https://github.com/user-attachments/assets/6de781d2-8662-447c-a20f-8842c1ddfa88

**Comment by zeitlings** [comment]
You're welcome! Regarding the custom URL schemes, it should be feasible to capture those as well, although there is a small potential risk of false positives in certain edge cases. I've added it to the list though!
